Database:
  type: MARIADB
  host: localhost
  database: clash_donations
  username: root
  password: password

Gui:
  package_gui:
    rows: 3
    title: "Packages"
    items:
      sign:
        item: 'SIGN'
        name: '&ePackages'
        data: 0
        lore:
          - ''
          - '&7Here will be displayed you purchased packages.'
          - ''
      available_package:
        item: 'STORAGE_MINECART'
        name: '%package_name%'
        data: 0
        lore:
          - '&7Click to authorize this purchase'
          - ''
          - '%package_details%'
          - ''
          - '&cIf you did not purchase this, please click this then click &4DECLINE'
      unvailable-package:
        item: 'MINECART'
        data: 0
        name: '&7&oYou do not have any claimable purchases'
        lore:
          - '&7Once you make a purchase on the store'
          - '&7you will need to accept them within this GUI'
  confirm_gui:
    rows: 3
    title: "Confirm your package"
    items:
      sign:
        item: 'SIGN'
        name: '&aCONFIRM ACTION'
        data: 0
        lore:
          - 'Confirming this package will result in responsibility'
          - 'Click Yes Or No'
      confirm_item:
        item: 'STAINED_GLASS'
        data: 5
        name: '&aConfirm'
        lore: []
      decline_item:
        item: 'STAINED_GLASS'
        data: 14
        name: '&cDecline'
        lore: []
Packages:
  Vip:
    placeholder_name: "&aVIP RANK &7(LifeTime)"
    placeholder_details: "&7Permanent rank, claimable each season"
    commands_on_accept:
      - '[console] pex user %name% group set vip'
    commands_on_decline:
      - '[message] &eStaff have been notified that this is an unauthorized purchase, no further action is required.'
    ban_commands:
      - '[console] ban %player% Chargeback -s'